name: Create Github Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: chrimaeon/github-create-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          publish: false
      - name: Notify Slack
        uses: chrimaeon/github-slack-action@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          text: "New draft release created for ${{ github.repository }}"
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New draft release created for ${{ github.repository }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Version*\n${{ github.ref_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*URL*\n${{ steps.create_release.outputs.html_url }}"
                  }
                ]
              }
            ]
