name: Build & Test

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DEVEO_USERNAME: ${{ secrets.DEVEO_USERNAME }}
      DEVEO_PASSWORD: ${{ secrets.DEVEO_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/build.gradle.kts', '**/Deps.kt') }}
      - name: Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Build & Test
        run: ./gradlew check koverReport koverVerify

      - name: Archive Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            **/build/reports/*
            **/build/test-results/*
      - name: Upload Codecov
        uses: codecov/codecov-action@v2
